### ISSUE TITLE
Example for file upload

### ISSUE THREAD

**Issue by abraxxa** [rshingleton/Mojo-Darkpan#2]
After having to read the code to find out how to upload a local file please add this example:

`curl -F 'pause99_add_uri_httpupload=@filename.tar.gz' http://localhost:3000/publish`

The term `deploy` is also misleading to me, I'd prefer `upload` or `publish`.

Thanks!

**Comment by rshingleton** [comment]
Sounds reasonable. I'll add them in.

**Comment by abraxxa** [comment]
Thanks!
