### ISSUE TITLE
other_versions key of list endpoint contains all tarballs

### ISSUE THREAD

**Issue by abraxxa** [rshingleton/Mojo-Darkpan#3]
For example:

```
{
  "D/DU/DUMMY/My-Dist-0.30.tar.gz": {
    "archive": "My-Dist0.30.tar.gz",
    "dir": "D/DU/DUMMY",
    "other_versions": [
      "Some-Other-Dist-1.79.tar.gz",
      "And-Another-Dist-0.038000.tar.gz"
    ],
    "version": "0.30"
  }
}
```

**Comment by rshingleton** [comment]
Ah I see. I'll take a look at this.

**Comment by rshingleton** [comment]
I think this is resolved. I found some bad regex where it was parsing the base package name and similarly named distributions by the same author could be mixed in. I changed how it does the parsing and pushed all the changes to CPAN and git
